version: "3.9"
services:
  lb:
    image: nginx:1.27-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "9999:9999"
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "600M"

  api-1: &api
    build: .
    environment:
      PORT: "9999"
      UPSTREAM_A_URL: "http://processor-a:8080"
      UPSTREAM_B_URL: "http://processor-b:8081"
      UPSTREAM_PAY_PATH: "/api/pay"
      AUTH_HEADER_NAME: "Authorization"
      AUTH_HEADER_VALUE: "Bearer 123"
      REQUEST_TIMEOUT_MS: "120"
      HEDGE_DELAY_MS: "40"
      CONCURRENCY_LIMIT: "1024"
      CB_FAIL_RATE: "0.25"
      CB_MIN_SAMPLES: "50"
      CB_OPEN_SECS: "2"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "450M"
    networks: [ default ]

  api-2:
    <<: *api

networks:
  default: {}
